# Generated by Django 3.0.5 on 2020-04-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixed_features_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Edit Later', max_length=25),
            preserve_default=False,
        ),
    ]
