# Generated by Django 3.0.5 on 2020-05-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixed_features_api', '0004_auto_20200505_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='../mixed_features/placeholder_image/profile-placeholder.jpg', null=True, upload_to='images'),
        ),
    ]
